# Site settings
author: Spencer A Cambern
title: Joureny through progress
header-img: img/home-bg.png
email: cambern134@gmail.com
copyright_name: Spencer A Cambern
description: > # this means to ignore newlines until "baseurl:"
  My learning experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cambe134

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
